### ISSUE TITLE
Can't scroll

### ISSUE THREAD

**Issue by 0xLevin** [basecom/MWPhotoBrowser#1]
1, the use of local pictures
2, the first to use the Grid view, and then click on the image, random rolling a few times, then cut back to the Grid view, and then can't scroll

demo:
https://youtu.be/vAhcxQuC-QM
https://vimeo.com/126620112

**Comment by mRs-** [comment]
1. You can hand in NSURL in each object. If you want to use local pictures just hand in the local NSURL.

`[photos addObject:[MWPhoto photoWithURL:[NSURL fileURLWithPath:[[NSBundle mainBundle] pathForResource:@"photo2l" ofType:@"jpg"]]]];`

The second issue is probably a bug. I will look into this and fix this as soon as possible.

**Comment by mRs-** [comment]
fixed the issue in the scroll_bug branch https://github.com/basecom/MWPhotoBrowser/tree/feature/scroll_bug
